// Manual type definitions for Prisma enums
// Generated from prisma/schema.prisma

export enum UserRole {
  COMPANY = 'COMPANY',
  DIVISIONAL = 'DIVISIONAL',
  REGIONAL = 'REGIONAL',
  CENTRAL = 'CENTRAL',
}

export enum DeclarationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  DIVISION_APPROVED = 'DIVISION_APPROVED',
  REGION_APPROVED = 'REGION_APPROVED',
  FINAL_APPROVED = 'FINAL_APPROVED',
  REJECTED = 'REJECTED',
}

export enum NotificationStatus {
  SENT = 'SENT',
  FAILED = 'FAILED',
  BOUNCED = 'BOUNCED',
  OPENED = 'OPENED',
}

export enum MovementType {
  RECRUITMENT = 'RECRUITMENT',
  PROMOTION = 'PROMOTION',
  DISMISSAL = 'DISMISSAL',
  RETIREMENT = 'RETIREMENT',
  DEATH = 'DEATH',
}

export enum ValidationStepType {
  GENDER_SUM = 'GENDER_SUM',
  CATEGORY_SUM = 'CATEGORY_SUM',
  MOVEMENT_CONSISTENCY = 'MOVEMENT_CONSISTENCY',
  WORKFORCE_GROWTH = 'WORKFORCE_GROWTH',
  EMPLOYEE_VALIDATION = 'EMPLOYEE_VALIDATION',
  OVERALL_CONSISTENCY = 'OVERALL_CONSISTENCY',
}
