import { QuestionnairesService } from './questionnaires.service';
import { PrismaService } from '../prisma/prisma.service';
import { CspCategory, VulnerableType } from '../types/prisma.types';
import { normalizeFlatKeys, buildNestedDto } from '../common/normalizers/flat-key-normalizer';

// Phase 1 (Projects & Programs) structural regression coverage.
//
// Section 4 (S4Q01-S4Q06) reuses the existing CSP row infrastructure
// (cadres/foremen/workers) directly — this proves that reuse actually
// reaches the fact-row builders under PP's own pp_s4qNN prefixes, and
// that S4Q05/S4Q06 correctly land in the disabilityData/vulnerableData
// relations without needing any new enum values (VulnerableType already
// had CADRES_VULN/FOREMEN_VULN/WORKERS_VULN/TOTAL_VULN before this phase).
describe('QuestionnairesService — Projects & Programs (Phase 1 structural)', () => {
  const service = new QuestionnairesService({} as PrismaService);

  it('CspCategory/VulnerableType (generated by `prisma generate`) still contain the '
    + 'plain CSP values Projects & Programs relies on', () => {
    const cadres: CspCategory = 'CADRES' as CspCategory;
    const cadresVuln: VulnerableType = 'CADRES_VULN' as VulnerableType;
    expect([cadres, cadresVuln]).toEqual(['CADRES', 'CADRES_VULN']);
  });

  it('buildCspGenderAgeRows produces CADRES/FOREMEN/WORKERS rows for S4Q01-S4Q04 prefixes', () => {
    const flat = {
      pp_s4q01_cadres_male_15_24: 3,
      pp_s4q03_workers_female_25_34: 2,
    };
    const rows: any[] = (service as any).buildCspGenderAgeRows(
      flat,
      [
        { prefix: 'pp_s4q01', tableName: 'pp_s4q01' },
        { prefix: 'pp_s4q02', tableName: 'pp_s4q02' },
        { prefix: 'pp_s4q03', tableName: 'pp_s4q03' },
        { prefix: 'pp_s4q04', tableName: 'pp_s4q04' },
      ],
      ['cadres', 'foremen', 'workers'],
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ tableName: 'pp_s4q01', cspCategory: 'CADRES', gender: 'MALE', value: 3 }),
      expect.objectContaining({ tableName: 'pp_s4q03', cspCategory: 'WORKERS', gender: 'FEMALE', value: 2 }),
    ]));
    // Never SFP — Administration's category set must not leak into PP.
    expect(rows.some((r) => ['FONCTIONNAIRE', 'DECISIONNAIRE', 'CONTRACTUELLE'].includes(r.cspCategory))).toBe(false);
  });

  it('buildDisabilityRows (S4Q05) produces plain CspCategory rows under the pp_s4q05 prefix', () => {
    const flat = { pp_s4q05_cadres_permanent_male: 1 };
    const rows: any[] = (service as any).buildDisabilityRows(flat, 'pp_s4q05');
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ cspCategory: 'CADRES', status: 'PERMANENT', gender: 'MALE', value: 1 }),
    ]));
  });

  it('buildCspVulnerableRows (S4Q06) maps CSP rows onto the existing '
    + 'CADRES_VULN/FOREMEN_VULN/WORKERS_VULN/TOTAL_VULN VulnerableType values '
    + '(no schema change needed — these were unused, not new)', () => {
    const flat = {
      pp_s4q06_cadres_permanent_male: 2,
      pp_s4q06_total_temporary_female: 5,
    };
    const rows: any[] = (service as any).buildCspVulnerableRows(flat, 'pp_s4q06');
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ vulnerableType: 'CADRES_VULN', status: 'PERMANENT', gender: 'MALE', value: 2 }),
      expect.objectContaining({ vulnerableType: 'TOTAL_VULN', status: 'TEMPORARY', gender: 'FEMALE', value: 5 }),
    ]));
  });
});

// Normalizer round-trip: proves Section 1 fields, Section 2's variable-
// count activities (with empty-row filtering), and Section 3's outcomes
// grid all survive normalizeFlatKeys -> buildNestedDto intact.
describe('flat-key-normalizer — Projects & Programs', () => {
  it('normalizes PP_S1Q01-16 camelCase input into registry keys', () => {
    const raw = {
      nature: '2',
      projectProgramName: 'Programme Test',
      personInCharge: 'Jean Dupont',
      area: '1',
      region: 'Centre',
      status: '2',
      permanentWorkers: '5',
      vacancies: '1',
    };
    const normalized = normalizeFlatKeys(raw, 'projectProgram');
    expect(normalized['PP_S1Q01']).toBe('2');
    expect(normalized['PP_S1Q02']).toBe('Programme Test');
    expect(normalized['PP_S1Q04']).toBe('Jean Dupont');
    expect(normalized['PP_S1Q13']).toBe('2');
    expect(normalized['PP_S1Q15']).toBe('5');
  });

  it('buildNestedDto drops empty activity rows and keeps filled ones with correct rowIndex-free shape', () => {
    const normalized: Record<string, unknown> = {
      s2_row1_description: 'Formation en couture',
      s2_row1_targetPopulation: '3',
      // row 2 entirely empty — must be dropped
      s2_row3_duration: '6',
    };
    const nested = buildNestedDto(normalized, 'projectProgram');
    const activities = nested['activities'] as Record<string, unknown>[];
    expect(activities.length).toBe(2);
    expect(activities[0]).toEqual({ description: 'Formation en couture', targetPopulation: '3' });
    expect(activities[1]).toEqual({ duration: '6' });
  });

  it('buildNestedDto maps Section 3 outcomes (4 rows x 3 periods) correctly', () => {
    const normalized: Record<string, unknown> = {
      s3kpi_employed_current: 10,
      s3kpi_employed_outlook_dec: 12,
      s3kpi_trained_outlook_june: 4,
    };
    const nested = buildNestedDto(normalized, 'projectProgram');
    const outcomes = nested['outcomes'] as Record<string, any>;
    expect(outcomes.employed).toEqual({ current: 10, outlookDec: 12 });
    expect(outcomes.trained).toEqual({ outlookJune: 4 });
    // Rows with no data at all should not appear.
    expect(outcomes.self_employed).toBeUndefined();
  });

  it('buildNestedDto does NOT populate the shared enterprise-family S2-S4 fields for projectProgram', () => {
    const nested = buildNestedDto({}, 'projectProgram');
    expect(nested['jobApplications']).toBeUndefined();
    expect(nested['departures']).toBeUndefined();
  });

  it('regression: administration/enterprise normalization unaffected', () => {
    const normalized = normalizeFlatKeys({ hasProject: 'Oui/ Yes' }, 'administration');
    expect(normalized['ADMIN_S1Q09']).toBe('Oui/ Yes');
    const nested = buildNestedDto(normalized, 'administration');
    expect((nested['administration'] as any).hasProject).toBe(1);
  });
});
