import { BadRequestException } from '@nestjs/common';
import { QuestionnairesService } from './questionnaires.service';
import { PrismaService } from '../prisma/prisma.service';
import { CspCategory } from '../types/prisma.types';

// Phase 2 P0 fix regression coverage.
//
// P0-B: the Postgres/Prisma CspCategory enum was missing FONCTIONNAIRE/
// DECISIONNAIRE/CONTRACTUELLE, so any Administration submission whose
// S21Q01/S22Q01/S3Q01 fact rows actually reached Prisma would have been
// rejected at runtime by Prisma's own enum validation.
//
// P0-A: separately, the frontend hardcoded CSP row keys (cadres/foremen/
// workers) regardless of entity type, so those SFP-keyed flat values
// never existed in the payload in the first place — buildCspGenderAgeRows/
// buildDepartureRows read them as 0 and silently produced zero rows,
// masking P0-B (no crash, but Administration recruitment/departure data
// was discarded).
//
// This file protects both ends of that chain: (1) once the frontend
// sends correctly-named SFP flat keys, the fact-row builders must
// produce FONCTIONNAIRE/DECISIONNAIRE/CONTRACTUELLE rows (not silently
// zero them out), and (2) those three literals must be valid values of
// the Prisma-generated CspCategory type — a compile error here would
// mean the schema/migration change was not actually picked up by
// `prisma generate`.
describe('QuestionnairesService — Administration SFP fact rows', () => {
  // buildCspGenderAgeRows/buildDepartureRows are pure functions of `flat`
  // (no Prisma calls), so a stub PrismaService is enough to construct the
  // service — this exercises the private builders directly, without a
  // live database, the same way establishment-id.generator.spec.ts tests
  // EstablishmentIdGenerator against a mocked PrismaService.
  const service = new QuestionnairesService({} as PrismaService);
  const sfpCategories = ['fonctionnaire', 'decisionnaire', 'contractuelle'];

  it('CspCategory (generated by `prisma generate` from the updated schema) '
    + 'includes all three SFP values', () => {
    // Compile-time check: these assignments only type-check if the
    // Prisma-generated enum actually contains these literals.
    const fonctionnaire: CspCategory = 'FONCTIONNAIRE' as CspCategory;
    const decisionnaire: CspCategory = 'DECISIONNAIRE' as CspCategory;
    const contractuelle: CspCategory = 'CONTRACTUELLE' as CspCategory;
    expect([fonctionnaire, decisionnaire, contractuelle]).toEqual([
      'FONCTIONNAIRE', 'DECISIONNAIRE', 'CONTRACTUELLE',
    ]);
  });

  it('buildCspGenderAgeRows emits FONCTIONNAIRE/DECISIONNAIRE/CONTRACTUELLE '
    + 'rows from correctly-named SFP flat keys (S21Q01/S22Q01)', () => {
    const flat = {
      s21q01_fonctionnaire_male_15_24: 5,
      s21q01_decisionnaire_female_25_34: 3,
      s21q01_contractuelle_male_35_plus: 2,
    };
    const rows: any[] = (service as any).buildCspGenderAgeRows(
      flat,
      [{ prefix: 's21q01', tableName: 's21q01' }],
      sfpCategories,
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ cspCategory: 'FONCTIONNAIRE', gender: 'MALE', value: 5 }),
      expect.objectContaining({ cspCategory: 'DECISIONNAIRE', gender: 'FEMALE', value: 3 }),
      expect.objectContaining({ cspCategory: 'CONTRACTUELLE', gender: 'MALE', value: 2 }),
    ]));
    // No stray CADRES/FOREMEN/WORKERS rows should ever appear when the
    // category list passed in is the SFP set.
    expect(rows.some((r) => ['CADRES', 'FOREMEN', 'WORKERS'].includes(r.cspCategory))).toBe(false);
  });

  it('buildDepartureRows emits FONCTIONNAIRE/DECISIONNAIRE/CONTRACTUELLE '
    + 'rows from correctly-named SFP flat keys (S3Q01)', () => {
    const flat = {
      s3q01_fonctionnaire_dismissal_male: 1,
      s3q01_decisionnaire_resignation_female: 2,
      s3q01_contractuelle_retirement_male: 4,
    };
    const rows: any[] = (service as any).buildDepartureRows(flat, [...sfpCategories, 'total']);
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ cspCategory: 'FONCTIONNAIRE', departureType: 'DISMISSAL', gender: 'MALE', value: 1 }),
      expect.objectContaining({ cspCategory: 'DECISIONNAIRE', departureType: 'RESIGNATION', gender: 'FEMALE', value: 2 }),
      expect.objectContaining({ cspCategory: 'CONTRACTUELLE', departureType: 'RETIREMENT', gender: 'MALE', value: 4 }),
    ]));
  });

  it('regression guard: CSP-keyed flat data (the pre-P0-A-fix frontend '
    + 'bug shape) produces NO rows when the SFP category list is used — '
    + 'documents the exact silent-data-loss failure mode this phase fixes', () => {
    const flat = {
      // Simulates the old broken frontend, which always sent cadres/
      // foremen/workers-keyed data regardless of entity type.
      s21q01_cadres_male_15_24: 7,
      s21q01_foremen_male_15_24: 1,
      s21q01_workers_male_15_24: 1,
    };
    const rows: any[] = (service as any).buildCspGenderAgeRows(
      flat,
      [{ prefix: 's21q01', tableName: 's21q01' }],
      sfpCategories,
    );
    expect(rows).toEqual([]);
  });

  it('does not regress the four existing entity types: CSP-keyed data '
    + 'still produces CADRES/FOREMEN/WORKERS rows with the default category list', () => {
    const flat = {
      s21q01_cadres_male_15_24: 5,
    };
    const rows: any[] = (service as any).buildCspGenderAgeRows(
      flat,
      [{ prefix: 's21q01', tableName: 's21q01' }],
      ['cadres', 'foremen', 'workers'],
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ cspCategory: 'CADRES', gender: 'MALE', value: 5 }),
    ]));
  });
});

// Phase 2 P0 fix regression coverage — entity-aware final-submission
// response-status validation.
//
// enforceFinalRequiredFields() used to check all 14 Enterprise-family
// *_RESPONSE_STATUS fields unconditionally for every entity type. Since
// Administration's AST excludes 6 of them (S22Q02/S22Q03/S23Q01/S23Q02/
// S3Q03/S4Q03) and Projects & Programs has none of the 14 except 3 that
// coincidentally share paper codes with its own S4Q01-Q03, a final
// (non-draft) submission for either entity always threw BadRequestException
// — confirmed by direct trace in the Phase 1.5 audit. This tests that
// FINAL_TABLE_RESPONSE_FIELDS_BY_ENTITY fixes that without weakening the
// existing all-14 requirement for Enterprise/Cooperative/CTD/ONG.
describe('QuestionnairesService — enforceFinalRequiredFields (entity-aware response-status)', () => {
  const service = new QuestionnairesService({} as PrismaService);

  const ALL_14_FIELDS = [
    'S21Q01_RESPONSE_STATUS', 'S22Q01_RESPONSE_STATUS', 'S22Q02_RESPONSE_STATUS',
    'S22Q03_RESPONSE_STATUS', 'S22Q04_RESPONSE_STATUS', 'S22Q05_RESPONSE_STATUS',
    'S23Q01_RESPONSE_STATUS', 'S23Q02_RESPONSE_STATUS', 'S3Q01_RESPONSE_STATUS',
    'S3Q02_RESPONSE_STATUS', 'S3Q03_RESPONSE_STATUS', 'S4Q01_RESPONSE_STATUS',
    'S4Q02_RESPONSE_STATUS', 'S4Q03_RESPONSE_STATUS',
  ];

  const ADMIN_APPLICABLE_FIELDS = [
    'S21Q01_RESPONSE_STATUS', 'S22Q01_RESPONSE_STATUS', 'S22Q04_RESPONSE_STATUS',
    'S22Q05_RESPONSE_STATUS', 'S3Q01_RESPONSE_STATUS', 'S3Q02_RESPONSE_STATUS',
    'S4Q01_RESPONSE_STATUS', 'S4Q02_RESPONSE_STATUS',
  ];
  const ADMIN_INAPPLICABLE_FIELDS = [
    'S22Q02_RESPONSE_STATUS', 'S22Q03_RESPONSE_STATUS', 'S23Q01_RESPONSE_STATUS',
    'S23Q02_RESPONSE_STATUS', 'S3Q03_RESPONSE_STATUS', 'S4Q03_RESPONSE_STATUS',
  ];

  const PP_APPLICABLE_FIELDS = [
    'S4Q01_RESPONSE_STATUS', 'S4Q02_RESPONSE_STATUS', 'S4Q03_RESPONSE_STATUS',
  ];
  const PP_INAPPLICABLE_FIELDS = [
    'S21Q01_RESPONSE_STATUS', 'S22Q01_RESPONSE_STATUS', 'S22Q02_RESPONSE_STATUS',
    'S22Q03_RESPONSE_STATUS', 'S22Q04_RESPONSE_STATUS', 'S22Q05_RESPONSE_STATUS',
    'S23Q01_RESPONSE_STATUS', 'S23Q02_RESPONSE_STATUS', 'S3Q01_RESPONSE_STATUS',
    'S3Q02_RESPONSE_STATUS', 'S3Q03_RESPONSE_STATUS',
  ];

  const validRespondent = { name: 'Jean Dupont', function: 'Directeur', phone1: '699999999', email: 'a@b.com' };

  function flatWithStatuses(fields: string[], omit: string[] = []): Record<string, unknown> {
    const flat: Record<string, unknown> = {};
    for (const f of fields) {
      if (!omit.includes(f)) flat[f] = 'REPORTED';
    }
    return flat;
  }

  function callEnforce(data: Record<string, unknown>, flat: Record<string, unknown>, entityType: string) {
    return (service as any).enforceFinalRequiredFields(data, flat, entityType);
  }

  const enterpriseData = {
    respondent: validRespondent,
    enterprise: {
      name: 'ACME', legalStatus: 'SARL', area: 1, region: 'Centre', department: 'Mfoundi',
      subdivision: 'Yaoundé 1', locality: 'Bastos', phone1: '699999999', poBox: 'BP 1',
      sector: 1, branch: 'Commerce', mainActivity: 'Vente', headOffice: 'Yaoundé',
      permanentWorkers: 10, vacancies: 2, size: 1,
    },
  };

  const administrationData = {
    respondent: validRespondent,
    administration: {
      name: 'MINEFOP', area: 1, region: 'Centre', department: 'Mfoundi', subdivision: 'Yaoundé 1',
      locality: 'Centre-ville', phone1: '699999999', sector: 1, mainMission: 'Emploi',
      hasProject: 1, hasSupervisedStructures: 2,
    },
  };

  const projectProgramData = {
    respondent: validRespondent,
    projectProgram: {
      nature: 1, name: 'Programme Test', personInCharge: 'Marie Curie', area: 1, region: 'Centre',
      department: 'Mfoundi', subdivision: 'Yaoundé 1', locality: 'Centre-ville', phone1: '699999999',
      poBox: 'BP 1', sector: 1, branch: 'Formation', mainMission: 'Insertion', headOffice: 'Yaoundé',
      supervisingMinistry: 'MINEFOP', status: 2, permanentWorkers: 5, vacancies: 1,
    },
  };

  it('Enterprise: a final submission missing S21Q01_RESPONSE_STATUS still fails (existing behavior preserved)', () => {
    const flat = flatWithStatuses(ALL_14_FIELDS, ['S21Q01_RESPONSE_STATUS']);
    expect(() => callEnforce(enterpriseData, flat, 'enterprise')).toThrow(BadRequestException);
  });

  it('Enterprise: all 14 fields present passes (baseline)', () => {
    const flat = flatWithStatuses(ALL_14_FIELDS);
    expect(() => callEnforce(enterpriseData, flat, 'enterprise')).not.toThrow();
  });

  it.each(['cooperative', 'ctd', 'ong'])(
    '%s: still requires all 14 response-status fields (existing behavior preserved)',
    (entityType) => {
      const flat = flatWithStatuses(ALL_14_FIELDS, ['S3Q03_RESPONSE_STATUS']);
      const data: Record<string, unknown> = { respondent: validRespondent, [entityType]: enterpriseData.enterprise };
      expect(() => callEnforce(data, flat, entityType)).toThrow(BadRequestException);
    },
  );

  it('Administration: absence of the 6 inapplicable response-status fields does NOT block final submission', () => {
    const flat = flatWithStatuses(ADMIN_APPLICABLE_FIELDS);
    // Sanity: none of the inapplicable fields are present at all.
    for (const f of ADMIN_INAPPLICABLE_FIELDS) expect(flat[f]).toBeUndefined();
    expect(() => callEnforce(administrationData, flat, 'administration')).not.toThrow();
  });

  it('Administration: a genuinely applicable response-status field, if missing, is still validated', () => {
    const flat = flatWithStatuses(ADMIN_APPLICABLE_FIELDS, ['S22Q01_RESPONSE_STATUS']);
    expect(() => callEnforce(administrationData, flat, 'administration')).toThrow(BadRequestException);
  });

  it('Projects & Programs: absence of all 11 Enterprise-family-only response-status fields does NOT block final submission', () => {
    const flat = flatWithStatuses(PP_APPLICABLE_FIELDS);
    for (const f of PP_INAPPLICABLE_FIELDS) expect(flat[f]).toBeUndefined();
    expect(() => callEnforce(projectProgramData, flat, 'projectProgram')).not.toThrow();
  });

  it('Projects & Programs: its own applicable response-status field (S4Q02), if missing, is still validated', () => {
    const flat = flatWithStatuses(PP_APPLICABLE_FIELDS, ['S4Q02_RESPONSE_STATUS']);
    expect(() => callEnforce(projectProgramData, flat, 'projectProgram')).toThrow(BadRequestException);
  });

  it("Projects & Programs: FINAL_REQUIRED_FIELDS['projectProgram'] remains enforced independently of the response-status fix", () => {
    const flat = flatWithStatuses(PP_APPLICABLE_FIELDS);
    const incompleteData = {
      respondent: validRespondent,
      projectProgram: { ...projectProgramData.projectProgram, name: '' },
    };
    expect(() => callEnforce(incompleteData, flat, 'projectProgram')).toThrow(BadRequestException);
  });
});

// P1 audit fix regression coverage.
//
// resolveGeoFields() (extracted from the inline chains that used to live
// directly in submitQuestionnaire) picks the submitting entity's region/
// department/subdivision/sector out of whichever one of the six per-entity
// DTO branches is present. Before this fix, the PROJECT_PROGRAM branch was
// missing from all four chains, so every Projects & Programs submission
// got a null region/department on OnefopSubmission — invisible to
// REGIONAL/DIVISIONAL reviewer queues (onefop.service.ts's role-based
// `where.region`/`where.department` filters) even though the entity's own
// detail record had the correct region all along. This locks in that
// PROJECT_PROGRAM resolves exactly like the other five, and guards against
// a future refactor silently dropping it again.
describe('QuestionnairesService — resolveGeoFields (P1: geo resolution per entity)', () => {
  const service = new QuestionnairesService({} as PrismaService);
  const resolve = (entityForGeo: any) => (service as any).resolveGeoFields(entityForGeo);

  it('resolves region/department/subdivision/sector from projectProgram when it is the only entity branch present', () => {
    const result = resolve({
      projectProgram: {
        region: 'Centre', department: 'Mfoundi', subdivision: 'Yaoundé 1er', sector: 'Éducation',
      },
    });
    expect(result).toEqual({
      region: 'Centre', department: 'Mfoundi', subdivision: 'Yaoundé 1er', sector: 'Éducation',
    });
  });

  it.each([
    ['enterprise'], ['cooperative'], ['ctd'], ['ong'], ['administration'], ['projectProgram'],
  ])('resolves geo fields from the %s branch when it is the only one present', (key) => {
    const result = resolve({
      [key]: { region: 'Littoral', department: 'Wouri', subdivision: 'Douala 1er', sector: 'Commerce' },
    });
    expect(result).toEqual({
      region: 'Littoral', department: 'Wouri', subdivision: 'Douala 1er', sector: 'Commerce',
    });
  });

  it('returns nulls (not a thrown error) when no entity branch is present, for every field', () => {
    expect(resolve({})).toEqual({ region: null, department: null, subdivision: null, sector: null });
  });

  it('does not let projectProgram override an earlier branch when both are present (documents precedence order)', () => {
    const result = resolve({
      enterprise: { region: 'Nord', department: 'Bénoué', subdivision: 'Garoua 1er', sector: 'Agriculture' },
      projectProgram: { region: 'Centre', department: 'Mfoundi', subdivision: 'Yaoundé 1er', sector: 'Éducation' },
    });
    expect(result).toEqual({
      region: 'Nord', department: 'Bénoué', subdivision: 'Garoua 1er', sector: 'Agriculture',
    });
  });
});
