import { QuestionnairesService } from './questionnaires.service';
import { PrismaService } from '../prisma/prisma.service';
import { CspCategory } from '../types/prisma.types';

// Phase 2 P0 fix regression coverage.
//
// P0-B: the Postgres/Prisma CspCategory enum was missing FONCTIONNAIRE/
// DECISIONNAIRE/CONTRACTUELLE, so any Administration submission whose
// S21Q01/S22Q01/S3Q01 fact rows actually reached Prisma would have been
// rejected at runtime by Prisma's own enum validation.
//
// P0-A: separately, the frontend hardcoded CSP row keys (cadres/foremen/
// workers) regardless of entity type, so those SFP-keyed flat values
// never existed in the payload in the first place — buildCspGenderAgeRows/
// buildDepartureRows read them as 0 and silently produced zero rows,
// masking P0-B (no crash, but Administration recruitment/departure data
// was discarded).
//
// This file protects both ends of that chain: (1) once the frontend
// sends correctly-named SFP flat keys, the fact-row builders must
// produce FONCTIONNAIRE/DECISIONNAIRE/CONTRACTUELLE rows (not silently
// zero them out), and (2) those three literals must be valid values of
// the Prisma-generated CspCategory type — a compile error here would
// mean the schema/migration change was not actually picked up by
// `prisma generate`.
describe('QuestionnairesService — Administration SFP fact rows', () => {
  // buildCspGenderAgeRows/buildDepartureRows are pure functions of `flat`
  // (no Prisma calls), so a stub PrismaService is enough to construct the
  // service — this exercises the private builders directly, without a
  // live database, the same way establishment-id.generator.spec.ts tests
  // EstablishmentIdGenerator against a mocked PrismaService.
  const service = new QuestionnairesService({} as PrismaService);
  const sfpCategories = ['fonctionnaire', 'decisionnaire', 'contractuelle'];

  it('CspCategory (generated by `prisma generate` from the updated schema) '
    + 'includes all three SFP values', () => {
    // Compile-time check: these assignments only type-check if the
    // Prisma-generated enum actually contains these literals.
    const fonctionnaire: CspCategory = 'FONCTIONNAIRE' as CspCategory;
    const decisionnaire: CspCategory = 'DECISIONNAIRE' as CspCategory;
    const contractuelle: CspCategory = 'CONTRACTUELLE' as CspCategory;
    expect([fonctionnaire, decisionnaire, contractuelle]).toEqual([
      'FONCTIONNAIRE', 'DECISIONNAIRE', 'CONTRACTUELLE',
    ]);
  });

  it('buildCspGenderAgeRows emits FONCTIONNAIRE/DECISIONNAIRE/CONTRACTUELLE '
    + 'rows from correctly-named SFP flat keys (S21Q01/S22Q01)', () => {
    const flat = {
      s21q01_fonctionnaire_male_15_24: 5,
      s21q01_decisionnaire_female_25_34: 3,
      s21q01_contractuelle_male_35_plus: 2,
    };
    const rows: any[] = (service as any).buildCspGenderAgeRows(
      flat,
      [{ prefix: 's21q01', tableName: 's21q01' }],
      sfpCategories,
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ cspCategory: 'FONCTIONNAIRE', gender: 'MALE', value: 5 }),
      expect.objectContaining({ cspCategory: 'DECISIONNAIRE', gender: 'FEMALE', value: 3 }),
      expect.objectContaining({ cspCategory: 'CONTRACTUELLE', gender: 'MALE', value: 2 }),
    ]));
    // No stray CADRES/FOREMEN/WORKERS rows should ever appear when the
    // category list passed in is the SFP set.
    expect(rows.some((r) => ['CADRES', 'FOREMEN', 'WORKERS'].includes(r.cspCategory))).toBe(false);
  });

  it('buildDepartureRows emits FONCTIONNAIRE/DECISIONNAIRE/CONTRACTUELLE '
    + 'rows from correctly-named SFP flat keys (S3Q01)', () => {
    const flat = {
      s3q01_fonctionnaire_dismissal_male: 1,
      s3q01_decisionnaire_resignation_female: 2,
      s3q01_contractuelle_retirement_male: 4,
    };
    const rows: any[] = (service as any).buildDepartureRows(flat, [...sfpCategories, 'total']);
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ cspCategory: 'FONCTIONNAIRE', departureType: 'DISMISSAL', gender: 'MALE', value: 1 }),
      expect.objectContaining({ cspCategory: 'DECISIONNAIRE', departureType: 'RESIGNATION', gender: 'FEMALE', value: 2 }),
      expect.objectContaining({ cspCategory: 'CONTRACTUELLE', departureType: 'RETIREMENT', gender: 'MALE', value: 4 }),
    ]));
  });

  it('regression guard: CSP-keyed flat data (the pre-P0-A-fix frontend '
    + 'bug shape) produces NO rows when the SFP category list is used — '
    + 'documents the exact silent-data-loss failure mode this phase fixes', () => {
    const flat = {
      // Simulates the old broken frontend, which always sent cadres/
      // foremen/workers-keyed data regardless of entity type.
      s21q01_cadres_male_15_24: 7,
      s21q01_foremen_male_15_24: 1,
      s21q01_workers_male_15_24: 1,
    };
    const rows: any[] = (service as any).buildCspGenderAgeRows(
      flat,
      [{ prefix: 's21q01', tableName: 's21q01' }],
      sfpCategories,
    );
    expect(rows).toEqual([]);
  });

  it('does not regress the four existing entity types: CSP-keyed data '
    + 'still produces CADRES/FOREMEN/WORKERS rows with the default category list', () => {
    const flat = {
      s21q01_cadres_male_15_24: 5,
    };
    const rows: any[] = (service as any).buildCspGenderAgeRows(
      flat,
      [{ prefix: 's21q01', tableName: 's21q01' }],
      ['cadres', 'foremen', 'workers'],
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ cspCategory: 'CADRES', gender: 'MALE', value: 5 }),
    ]));
  });
});
