/*
  Warnings:

  - The values [HEAD,DEPUTY_HEAD,DIVISION_HEAD,SUB_DIRECTION_HEAD,OFFICER,ASSISTANT,TECHNICIAN,ADMIN] on the enum `PositionType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "PositionType_new" AS ENUM ('MINISTRE', 'CHEF_SECRETARIAT_PARTICULIER', 'CONSEILLER_TECHNIQUE', 'INSPECTEUR_GENERAL_SERVICES', 'INSPECTEUR_GENERAL_FORMATIONS', 'INSPECTEUR_SERVICES', 'INSPECTEUR_FORMATIONS', 'ATTACHE_PEDAGOGIQUE', 'SECRETAIRE_GENERAL', 'DIRECTEUR', 'CHEF_DIVISION', 'SOUS_DIRECTEUR', 'CHEF_SERVICE', 'CHEF_CELLULE', 'CHEF_BUREAU', 'CHARGE_ETUDES_ASSISTANT', 'DELEGUE_REGIONAL', 'INSPECTEUR_REGIONAL_FORMATIONS', 'CONSEILLER_REGIONAL_FORMATIONS', 'DELEGUE_DEPARTEMENTAL', 'RESPONSABLE_STRUCTURE_FORMATION');
ALTER TABLE "service_positions" ALTER COLUMN "positionType" TYPE "PositionType_new" USING ("positionType"::text::"PositionType_new");
ALTER TABLE "users" ALTER COLUMN "positionType" TYPE "PositionType_new" USING ("positionType"::text::"PositionType_new");
ALTER TYPE "PositionType" RENAME TO "PositionType_old";
ALTER TYPE "PositionType_new" RENAME TO "PositionType";
DROP TYPE "PositionType_old";
COMMIT;
