// src/lib/onefop-schema.ts
//
// TypeScript shape of assets/schemas/onefop.schema.json — generated by
// test/tools/export_onefop_schema_test.dart from the canonical
// lib/core/focus/compiler/onefop_ast.dart. This file only describes the
// shape; it must never redefine field content. If the schema's shape
// changes, update these types to match the generator's actual output —
// never patch the JSON by hand.

export interface LocalizedText {
  fr: string;
  en: string;
}

export interface FieldOption {
  value: string;
  label: LocalizedText | null;
}

export interface FieldVisibility {
  dependsOn: string;
  dependsValue: string | null;
  dependsOperator: "eq" | "contains" | "in";
  dependsValues?: string[];
}

export type VtCellKind = "number" | "text" | "radioCode" | "boolean" | "computed";

export interface VtCellOption {
  value: string;
  code: string;
  label: LocalizedText | null;
}

export interface VtCellDef {
  key: string;
  label: LocalizedText | null;
  kind: VtCellKind;
  required: boolean;
  dependsOnKey: string | null;
  options: VtCellOption[] | null;
  /** "sum-of-siblings" for kind === "computed", null otherwise — see
   * onefop.schema.json's top-level `formulas` block for what it means. */
  formula: string | null;
}

export interface VtRowDef {
  id: string;
  label: LocalizedText | null;
  labelFromCells: string[] | null;
}

export interface VtTableMeta {
  paperCode: string | null;
  title: LocalizedText | null;
  progressNoun: LocalizedText | null;
  isRoster: boolean;
  progressiveRows: boolean;
  singleCellPerRow: boolean;
  rows: VtRowDef[];
  cells: VtCellDef[];
}

export interface OnefopTable {
  id: string;
  template: string | null;
  rowKeys: string[] | null;
  csps?: string[] | null;
  /**
   * Declared status dimension (e.g. ["permanent","temporary"]). An empty
   * array means the table has no status dimension — Administration S21Q03
   * (catégorie × sexe) and S21Q04 (nature × sexe). Absent = template default.
   */
  statuses?: string[] | null;
  rowCapacity: number | null;
  matrix: string[][] | null;
  // Built from the same VtTableDef/VtCellDef Flutter's own VT widgets
  // render from (vtTableDefFor, vt_table_defs.dart) — confirmed this
  // session not to drift from what's actually on screen, unlike the
  // classic (non-VT) templates' matrix/labels.
  vt?: VtTableMeta;
  limitation?: string;
}

export interface OnefopField {
  id: string;
  paperCode: string | null;
  path: string | null;
  type: string;
  required: boolean;
  label: LocalizedText | null;
  hint: LocalizedText | null;
  instruction: LocalizedText | null;
  options: FieldOption[] | null;
  visibility: FieldVisibility | null;
  table: OnefopTable | null;
}

export interface OnefopSubsection {
  title: LocalizedText | null;
  fieldIds: string[];
}

export interface OnefopSection {
  id: string;
  order: number | null;
  title: LocalizedText | null;
  description: LocalizedText | null;
  entityTypes: string[] | null;
  subsections: OnefopSubsection[];
  fields: OnefopField[];
}

export interface OnefopEntity {
  entityType: string;
  sectionCount: number;
  fieldCount: number;
  tableCount: number;
  sections: OnefopSection[];
}

export interface OnefopSchema {
  schemaVersion: number;
  source: string;
  astTotals: { sections: number; questions: number };
  sectionEntityMap: Record<string, string[] | null>;
  formulas: Record<string, string>;
  entities: Record<string, OnefopEntity>;
}

export type FormData = Record<string, unknown>;

/** False only when the schema declares an explicitly empty status list. */
export function tableHasStatusDimension(table: Pick<OnefopTable, "statuses"> | null | undefined): boolean {
  return !(Array.isArray(table?.statuses) && table.statuses.length === 0);
}

/**
 * Evaluates field visibility based on schema rules.
 * Supports eq, contains, and in (dependsValues OR condition). Follows the
 * schema only: VT1_13 is asked for "Non-fonctionnelle" alone, as printed on
 * the form. A follow-up whose own parent is hidden cannot stay visible on a
 * stale answer, because hidden answers are erased as soon as the parent
 * changes (cleanHiddenDependentFields, applied by useOnefopDraft).
 */
export function isFieldVisible(field: OnefopField, data: FormData): boolean {
  const visibility = field.visibility;
  if (!visibility) return true;
  const trigger = data[visibility.dependsOn];

  if (visibility.dependsValues && Array.isArray(visibility.dependsValues)) {
    return typeof trigger === "string"
      ? visibility.dependsValues.some(
          (dv) => trigger === dv || trigger.startsWith(dv.split("/")[0].trim()),
        )
      : visibility.dependsValues.includes(trigger as string);
  }

  if (visibility.dependsOperator === "contains") {
    return Array.isArray(trigger) && trigger.includes(visibility.dependsValue);
  }
  if (typeof trigger === "string" && typeof visibility.dependsValue === "string") {
    if (trigger === visibility.dependsValue) return true;
    const prefix = visibility.dependsValue.split("/")[0].trim();
    if (trigger === prefix || trigger.startsWith(prefix)) return true;
  }
  return trigger === visibility.dependsValue;
}

/**
 * A training centre declared "Non-fonctionnelle" or "Fermée" in 1.12 answers
 * Section 1 only: Sections 2–9 describe an operating centre, so none of their
 * questions are required (the server applies the same rule).
 */
export function isVtSectionWaived(sectionId: string, data: FormData): boolean {
  if (!sectionId.endsWith("_vocationalTraining") || sectionId === "section1_vocationalTraining") return false;
  const status = data["VT1_12"];
  return typeof status === "string" && (status.startsWith("Non-fonctionnelle") || status.startsWith("Fermée"));
}

/**
 * Recursively removes values for fields that are conditionally hidden
 * based on current parent answers (D5 fix).
 * Prevents stale phantom values from surviving visibility toggles
 * and leaking into submission totals.
 */
export function cleanHiddenDependentFields(
  entity: OnefopEntity,
  data: FormData,
): FormData {
  const cleaned: FormData = { ...data };
  let changed = true;
  let iterations = 0;
  while (changed && iterations < 10) {
    changed = false;
    iterations++;
    for (const sec of entity.sections) {
      for (const field of sec.fields) {
        if (!isFieldVisible(field, cleaned)) {
          if (field.id in cleaned && cleaned[field.id] !== undefined) {
            delete cleaned[field.id];
            changed = true;
          }
          if (field.table?.matrix) {
            for (const row of field.table.matrix) {
              for (const cellId of row) {
                if (cellId in cleaned && cleaned[cellId] !== undefined) {
                  delete cleaned[cellId];
                  changed = true;
                }
              }
            }
          }
        }
      }
    }
  }
  return cleaned;
}

export function localized(text: LocalizedText | null, locale: "fr" | "en" = "fr"): string {
  if (!text) return "";
  return text[locale];
}

/** PDF-style bilingual presentation ("Français/ English") used throughout
 * the official ONEFOP forms — matches the plan's "FR-then-EN within the
 * same field" requirement by reusing the source documents' own convention
 * rather than inventing a different bilingual layout. */
export function bilingual(text: LocalizedText | null): string {
  if (!text) return "";
  if (text.fr === text.en) return text.fr;
  return `${text.fr}/ ${text.en}`;
}

/**
 * Mirrors OnefopFormController.isSimpleSection exactly: Section 0, every
 * entity's own Section 1, and all of Vocational Training's 9 sections show
 * their official paper question code in front of the label (see
 * fieldDisplayLabel below); the big Section 2-4 cross-tabulation tables for
 * every other entity don't — those paper codes already appear inside each
 * table's own question text/instruction instead.
 */
export function isSimpleSection(sectionId: string): boolean {
  return sectionId === "section0" || sectionId.startsWith("section1_") || sectionId.endsWith("_vocationalTraining");
}

/**
 * Mirrors buildFieldLabel (onefop_form_widgets.dart): prefixes the paper
 * code ("S1Q01 - ...") for simple sections, unless the label already
 * starts with it. Every label-rendering call site (FieldRenderer,
 * TableurShell) should go through this rather than calling bilingual()
 * directly, so the two presentation modes can't drift on this.
 */
export function fieldDisplayLabel(field: OnefopField, sectionId: string, locale?: "fr" | "en"): string {
  const label = locale ? localized(field.label, locale) : bilingual(field.label);
  if (isSimpleSection(sectionId) && field.paperCode && !label.startsWith(field.paperCode)) {
    return `${field.paperCode} - ${label}`;
  }
  return label;
}

/**
 * Which fields start a new subsection heading, in a section's real render
 * order — shared by every presentation mode that groups fields under
 * subsection headers (block layout, dense table layout, ...) so the
 * grouping logic itself is computed once, not duplicated per mode.
 */
export function computeSubsectionLayout(section: OnefopSection, locale?: "fr" | "en"): {
  headingByFieldId: Map<string, string>;
  startsHeadingFieldIds: Set<string>;
} {
  const headingByFieldId = new Map<string, string>();
  for (const sub of section.subsections) {
    const key = locale ? localized(sub.title, locale) : bilingual(sub.title);
    for (const id of sub.fieldIds) headingByFieldId.set(id, key);
  }

  const startsHeadingFieldIds = new Set<string>();
  let previous: string | null = null;
  for (const field of section.fields) {
    const sub = headingByFieldId.get(field.id) ?? null;
    if (sub !== null && sub !== previous) startsHeadingFieldIds.add(field.id);
    previous = sub;
  }

  return { headingByFieldId, startsHeadingFieldIds };
}
