"use client";

import React, { useState, useMemo, useCallback, useEffect } from "react";
import type { FormData, OnefopEntity } from "@/lib/onefop-schema";
import { TABLE_PREFIX_MAP, findKeysMatchingPrefixes, hasEnteredData } from "./ScopeDataManagement";

export interface ProjectProgramScopeQuizProps {
  entity: OnefopEntity;
  data: FormData;
  onChange: (fieldId: string, value?: unknown) => void;
  onComplete: () => void;
  onBack: () => void;
  locale?: "fr" | "en";
  establishmentName?: string;
  navigationRef?: React.MutableRefObject<{
    onPrev: () => boolean;
    onNext: () => boolean;
  } | null>;
}

export type OutcomeKey = "employed" | "self_employed" | "jobs_created" | "trained";
export type RecruitmentTypeKey = "permanent" | "temporary" | "disability" | "vulnerable";

interface ProjectProgramScopeConfig {
  completedAt?: string;
  noOutcomes: boolean;
  outcomes: OutcomeKey[];
  hasPermanentStaff: boolean | null;
  hasTemporaryStaff: boolean | null;
  hasRecruitment: boolean | null;
  recruitmentTypes: RecruitmentTypeKey[];
}

const OUTCOME_OPTIONS: { id: OutcomeKey; titleFr: string; titleEn: string; descFr: string; descEn: string }[] = [
  {
    id: "employed",
    titleFr: "Demandeurs d'emploi insérés en emploi salarié",
    titleEn: "Job seekers placed into salaried employment",
    descFr: "Bénéficiaires ayant accédé à un emploi salarié (CDI, CDD).",
    descEn: "Beneficiaries who obtained salaried employment (open-ended or fixed-term).",
  },
  {
    id: "self_employed",
    titleFr: "Demandeurs d'emploi insérés en auto-emploi",
    titleEn: "Job seekers placed into self-employment",
    descFr: "Bénéficiaires installés à leur propre compte ou créateurs d'activités indépendantes.",
    descEn: "Beneficiaries established in self-employment or micro-enterprises.",
  },
  {
    id: "jobs_created",
    titleFr: "Emplois créés à travers des micro-projets ou marchés publics financés",
    titleEn: "Jobs created through funded micro-projects or public contracts",
    descFr: "Emplois directs générés par les projets ou investissements soutenus par la structure.",
    descEn: "Direct jobs generated by projects or public procurement supported by the structure.",
  },
  {
    id: "trained",
    titleFr: "Personnes formées aux métiers ou développement de compétences",
    titleEn: "Persons trained in trades or skill development",
    descFr: "Bénéficiaires ayant suivi ou achevé une formation professionnelle qualifiante.",
    descEn: "Beneficiaries who completed vocational training or capacity building.",
  },
];

const RECRUITMENT_OPTIONS: { id: RecruitmentTypeKey; tableCode: string; titleFr: string; titleEn: string; descFr: string; descEn: string }[] = [
  {
    id: "permanent",
    tableCode: "S4Q03",
    titleFr: "Recrutement de personnel permanent (Tableau 4.3)",
    titleEn: "Recruitment of permanent staff (Table 4.3)",
    descFr: "Salariés recrutés sous contrat à durée indéterminée (CDI) ou statutaire.",
    descEn: "Staff recruited under open-ended contracts or civil service status.",
  },
  {
    id: "temporary",
    tableCode: "S4Q04",
    titleFr: "Recrutement de personnel temporaire (Tableau 4.4)",
    titleEn: "Recruitment of temporary staff (Table 4.4)",
    descFr: "Salariés recrutés sous CDD, vacataires, occasionnels ou saisonniers.",
    descEn: "Staff recruited under fixed-term, temporary, or seasonal contracts.",
  },
  {
    id: "disability",
    tableCode: "S4Q05",
    titleFr: "Recrutement de personnes en situation de handicap (Tableau 4.5)",
    titleEn: "Recruitment of persons with disabilities (Table 4.5)",
    descFr: "Personnes handicapées recrutées (en contrat permanent ou temporaire).",
    descEn: "Persons with disabilities recruited (permanent or temporary contract).",
  },
  {
    id: "vulnerable",
    tableCode: "S4Q06",
    titleFr: "Recrutement de personnes vulnérables (Tableau 4.6)",
    titleEn: "Recruitment of vulnerable persons (Table 4.6)",
    descFr: "Déplacés internes, réfugiés, orphelins ou populations vulnérables.",
    descEn: "Internally displaced persons, refugees, orphans, or vulnerable groups.",
  },
];

export function ProjectProgramScopeQuiz({
  entity,
  data,
  onChange,
  onComplete,
  onBack,
  locale = "fr",
  establishmentName,
  navigationRef,
}: ProjectProgramScopeQuizProps) {
  const isEn = locale === "en";

  // Pre-fill initial state from existing data._scopeConfig or heuristics
  const initialConfig = useMemo<ProjectProgramScopeConfig>(() => {
    const raw = data._scopeConfig;
    if (raw && typeof raw === "object" && "projectProgram" in raw) {
      const cfg = (raw as Record<string, unknown>).projectProgram as Partial<ProjectProgramScopeConfig>;
      return {
        completedAt: cfg.completedAt,
        noOutcomes: Boolean(cfg.noOutcomes),
        outcomes: Array.isArray(cfg.outcomes) ? cfg.outcomes : [],
        hasPermanentStaff: typeof cfg.hasPermanentStaff === "boolean" ? cfg.hasPermanentStaff : null,
        hasTemporaryStaff: typeof cfg.hasTemporaryStaff === "boolean" ? cfg.hasTemporaryStaff : null,
        hasRecruitment: typeof cfg.hasRecruitment === "boolean" ? cfg.hasRecruitment : null,
        recruitmentTypes: Array.isArray(cfg.recruitmentTypes) ? cfg.recruitmentTypes : [],
      };
    }

    // Heuristics from existing data
    const s1q15 = Number(data.PP_S1Q15 ?? data.s1q15);
    const hasPermHeuristic = !isNaN(s1q15) && s1q15 > 0 ? true : null;

    const s4q01Status = data.S4Q01_RESPONSE_STATUS ?? data.PP_S4Q01_RESPONSE_STATUS;
    const s4q02Status = data.S4Q02_RESPONSE_STATUS ?? data.PP_S4Q02_RESPONSE_STATUS;
    const s4q03Status = data.S4Q03_RESPONSE_STATUS ?? data.PP_S4Q03_RESPONSE_STATUS;
    const s4q04Status = data.S4Q04_RESPONSE_STATUS ?? data.PP_S4Q04_RESPONSE_STATUS;
    const s4q05Status = data.S4Q05_RESPONSE_STATUS ?? data.PP_S4Q05_RESPONSE_STATUS;
    const s4q06Status = data.S4Q06_RESPONSE_STATUS ?? data.PP_S4Q06_RESPONSE_STATUS;

    const hasPerm = s4q01Status === "REPORTED" ? true : s4q01Status === "NONE" ? false : hasPermHeuristic;
    const hasTemp = s4q02Status === "REPORTED" ? true : s4q02Status === "NONE" ? false : null;

    const anyRecruitReported =
      s4q03Status === "REPORTED" ||
      s4q04Status === "REPORTED" ||
      s4q05Status === "REPORTED" ||
      s4q06Status === "REPORTED";

    const allRecruitNone =
      s4q03Status === "NONE" &&
      s4q04Status === "NONE" &&
      s4q05Status === "NONE" &&
      s4q06Status === "NONE";

    const hasRec = anyRecruitReported ? true : allRecruitNone ? false : null;

    const recTypes: RecruitmentTypeKey[] = [];
    if (s4q03Status === "REPORTED") recTypes.push("permanent");
    if (s4q04Status === "REPORTED") recTypes.push("temporary");
    if (s4q05Status === "REPORTED") recTypes.push("disability");
    if (s4q06Status === "REPORTED") recTypes.push("vulnerable");

    // Check outcome cells
    const detectedOutcomes: OutcomeKey[] = [];
    (["employed", "self_employed", "jobs_created", "trained"] as OutcomeKey[]).forEach((k) => {
      const v = data[`s3kpi_${k}_current`];
      if (v !== undefined && v !== null && v !== "" && v !== 0 && v !== "0") {
        detectedOutcomes.push(k);
      }
    });

    return {
      noOutcomes: detectedOutcomes.length === 0 && (s4q01Status !== undefined || s4q03Status !== undefined),
      outcomes: detectedOutcomes,
      hasPermanentStaff: hasPerm,
      hasTemporaryStaff: hasTemp,
      hasRecruitment: hasRec,
      recruitmentTypes: recTypes,
    };
  }, [data]);

  const [noOutcomes, setNoOutcomes] = useState<boolean>(initialConfig.noOutcomes);
  const [outcomes, setOutcomes] = useState<OutcomeKey[]>(initialConfig.outcomes);
  const [hasPermanentStaff, setHasPermanentStaff] = useState<boolean | null>(initialConfig.hasPermanentStaff);
  const [hasTemporaryStaff, setHasTemporaryStaff] = useState<boolean | null>(initialConfig.hasTemporaryStaff);
  const [hasRecruitment, setHasRecruitment] = useState<boolean | null>(initialConfig.hasRecruitment);
  const [recruitmentTypes, setRecruitmentTypes] = useState<RecruitmentTypeKey[]>(initialConfig.recruitmentTypes);

  const [showPlausibilityModal, setShowPlausibilityModal] = useState(false);
  const [showDroppedDataModal, setShowDroppedDataModal] = useState(false);

  // Section 1 permanent headcount declaration for context
  const s1PermanentCount = useMemo(() => {
    const val = data.PP_S1Q15 ?? data.s1q15;
    if (val !== undefined && val !== null && val !== "") {
      const num = Number(val);
      return !isNaN(num) ? num : null;
    }
    return null;
  }, [data]);

  // Handle outcome selection toggle
  const toggleOutcome = (key: OutcomeKey) => {
    setNoOutcomes(false);
    setOutcomes((prev) =>
      prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]
    );
  };

  const handleSelectNoOutcomes = () => {
    setNoOutcomes(true);
    setOutcomes([]);
  };

  // Handle recruitment types toggle
  const toggleRecruitmentType = (key: RecruitmentTypeKey) => {
    setRecruitmentTypes((prev) =>
      prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]
    );
  };

  // Validation: check if all 3 parts have been answered
  const isPart1Complete = noOutcomes || outcomes.length > 0;
  const isPart2Complete = hasPermanentStaff !== null && hasTemporaryStaff !== null;
  const isPart3Complete =
    hasRecruitment === false || (hasRecruitment === true && recruitmentTypes.length > 0);

  const isFormComplete = isPart1Complete && isPart2Complete && isPart3Complete;

  // Global "None" check (respondent declaring no activities, no staff, no recruitments)
  const isGlobalNone =
    noOutcomes &&
    hasPermanentStaff === false &&
    hasTemporaryStaff === false &&
    hasRecruitment === false;

  // Check if any existing entered cell figures would be dropped by setting to NONE
  const hasDroppedDataWarning = useMemo(() => {
    const checkTable = (code: string, isReported: boolean) => {
      if (!isReported) {
        const prefixes = TABLE_PREFIX_MAP[code] ?? [code.toLowerCase() + "_", `pp_${code.toLowerCase()}_`];
        const keys = findKeysMatchingPrefixes(data, prefixes);
        return hasEnteredData(data, keys);
      }
      return false;
    };

    if (checkTable("PP_S4Q01", Boolean(hasPermanentStaff))) return true;
    if (checkTable("PP_S4Q02", Boolean(hasTemporaryStaff))) return true;
    if (checkTable("PP_S4Q03", Boolean(hasRecruitment && recruitmentTypes.includes("permanent")))) return true;
    if (checkTable("PP_S4Q04", Boolean(hasRecruitment && recruitmentTypes.includes("temporary")))) return true;
    if (checkTable("PP_S4Q05", Boolean(hasRecruitment && recruitmentTypes.includes("disability")))) return true;
    if (checkTable("PP_S4Q06", Boolean(hasRecruitment && recruitmentTypes.includes("vulnerable")))) return true;

    // Check S3 outcome cells
    if (noOutcomes) {
      const keys = ["s3kpi_employed_current", "s3kpi_self_employed_current", "s3kpi_jobs_created_current", "s3kpi_trained_current"];
      if (hasEnteredData(data, keys)) return true;
    } else {
      const allOutcomes: OutcomeKey[] = ["employed", "self_employed", "jobs_created", "trained"];
      for (const ok of allOutcomes) {
        if (!outcomes.includes(ok)) {
          const k = `s3kpi_${ok}_current`;
          if (hasEnteredData(data, [k])) return true;
        }
      }
    }

    return false;
  }, [data, hasPermanentStaff, hasTemporaryStaff, hasRecruitment, recruitmentTypes, noOutcomes, outcomes]);

  // Zero-out table cells for a table marked NONE
  const zeroTableCells = useCallback(
    (tablePaperCode: string) => {
      const s4 = entity.sections.find((s) => s.id === "section4_projectProgram");
      const field = s4?.fields.find(
        (f) =>
          f.paperCode?.toUpperCase() === tablePaperCode.toUpperCase() ||
          f.id.toUpperCase() === `PP_${tablePaperCode.toUpperCase()}`
      );
      if (field?.table?.matrix) {
        for (const row of field.table.matrix) {
          for (const cellKey of row) {
            onChange(cellKey, 0);
          }
        }
      } else {
        const rawPrefix = tablePaperCode.toLowerCase() + "_";
        const ppPrefix = "pp_" + rawPrefix;
        Object.keys(data).forEach((k) => {
          const lk = k.toLowerCase();
          if (lk.startsWith(rawPrefix) || lk.startsWith(ppPrefix)) {
            onChange(k, 0);
          }
        });
      }
    },
    [data, entity, onChange]
  );

  // Commit all quiz settings and table statuses
  const commitScopeData = useCallback(() => {
    // 1. Commit _scopeConfig
    const config: ProjectProgramScopeConfig = {
      completedAt: new Date().toISOString(),
      noOutcomes,
      outcomes,
      hasPermanentStaff,
      hasTemporaryStaff,
      hasRecruitment,
      recruitmentTypes,
    };
    onChange("_scopeConfig", {
      ...(typeof data._scopeConfig === "object" ? data._scopeConfig : {}),
      projectProgram: config,
    });

    // 2. Section 3 Outcome cells: zero unselected rows
    const allOutcomes: OutcomeKey[] = ["employed", "self_employed", "jobs_created", "trained"];
    for (const ok of allOutcomes) {
      if (noOutcomes || !outcomes.includes(ok)) {
        onChange(`s3kpi_${ok}_current`, 0);
      }
    }

    // 3. Section 4: S4Q01 to S4Q06 table statuses & cell zeroing
    const s4q01Status = hasPermanentStaff ? "REPORTED" : "NONE";
    onChange("S4Q01_RESPONSE_STATUS", s4q01Status);
    onChange("PP_S4Q01_RESPONSE_STATUS", s4q01Status);
    if (!hasPermanentStaff) zeroTableCells("S4Q01");

    const s4q02Status = hasTemporaryStaff ? "REPORTED" : "NONE";
    onChange("S4Q02_RESPONSE_STATUS", s4q02Status);
    onChange("PP_S4Q02_RESPONSE_STATUS", s4q02Status);
    if (!hasTemporaryStaff) zeroTableCells("S4Q02");

    const s4q03Status = hasRecruitment && recruitmentTypes.includes("permanent") ? "REPORTED" : "NONE";
    onChange("S4Q03_RESPONSE_STATUS", s4q03Status);
    onChange("PP_S4Q03_RESPONSE_STATUS", s4q03Status);
    if (s4q03Status === "NONE") zeroTableCells("S4Q03");

    const s4q04Status = hasRecruitment && recruitmentTypes.includes("temporary") ? "REPORTED" : "NONE";
    onChange("S4Q04_RESPONSE_STATUS", s4q04Status);
    onChange("PP_S4Q04_RESPONSE_STATUS", s4q04Status);
    if (s4q04Status === "NONE") zeroTableCells("S4Q04");

    const s4q05Status = hasRecruitment && recruitmentTypes.includes("disability") ? "REPORTED" : "NONE";
    onChange("S4Q05_RESPONSE_STATUS", s4q05Status);
    onChange("PP_S4Q05_RESPONSE_STATUS", s4q05Status);
    if (s4q05Status === "NONE") zeroTableCells("S4Q05");

    const s4q06Status = hasRecruitment && recruitmentTypes.includes("vulnerable") ? "REPORTED" : "NONE";
    onChange("S4Q06_RESPONSE_STATUS", s4q06Status);
    onChange("PP_S4Q06_RESPONSE_STATUS", s4q06Status);
    if (s4q06Status === "NONE") zeroTableCells("S4Q06");
  }, [
    data._scopeConfig,
    hasPermanentStaff,
    hasRecruitment,
    hasTemporaryStaff,
    noOutcomes,
    onChange,
    outcomes,
    recruitmentTypes,
    zeroTableCells,
  ]);

  const handleProceed = useCallback(() => {
    if (!isFormComplete) return;

    if (isGlobalNone) {
      setShowPlausibilityModal(true);
      return;
    }

    if (hasDroppedDataWarning) {
      setShowDroppedDataModal(true);
      return;
    }

    commitScopeData();
    onComplete();
  }, [commitScopeData, hasDroppedDataWarning, isFormComplete, isGlobalNone, onComplete]);

  // Hook navigationRef for wizard previous / next buttons
  useEffect(() => {
    if (!navigationRef) return;
    navigationRef.current = {
      onPrev: () => {
        onBack();
        return true;
      },
      onNext: () => {
        if (isFormComplete) {
          handleProceed();
          return true;
        }
        return false;
      },
    };
    return () => {
      navigationRef.current = null;
    };
  }, [navigationRef, onBack, isFormComplete, handleProceed]);

  return (
    <div
      style={{
        maxWidth: 960,
        margin: "0 auto",
        padding: "clamp(16px, 3vw, 28px) 0 48px",
        fontFamily: "var(--cam-font-sans, system-ui, sans-serif)",
      }}
    >
      {/* Quiz Banner / Header */}
      <div
        style={{
          background: "var(--cam-surface)",
          border: "1px solid var(--cam-border)",
          borderRadius: "var(--cam-radius-md, 8px)",
          padding: "clamp(20px, 3vw, 28px)",
          marginBottom: 24,
          boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
        }}
      >
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16, flexWrap: "wrap" }}>
          <div>
            <div
              style={{
                display: "inline-block",
                padding: "3px 10px",
                borderRadius: "var(--cam-radius-full, 9999px)",
                background: "rgba(30, 107, 58, 0.12)",
                color: "var(--cam-green)",
                fontSize: 12,
                fontWeight: 700,
                letterSpacing: "0.04em",
                textTransform: "uppercase",
                marginBottom: 10,
              }}
            >
              {isEn ? "Period Declaration Quiz" : "Quiz préalable de déclaration"}
            </div>
            <h1
              // Focus target of ModernJobsWizard when the quiz opens (useStepFocus).
              id="mj-scope-heading"
              tabIndex={-1}
              style={{
                outline: "none",
                fontSize: "clamp(20px, 3vw, 24px)",
                fontWeight: 800,
                margin: "0 0 8px",
                color: "var(--cam-text)",
                lineHeight: 1.25,
              }}
            >
              {isEn
                ? "Period Events — Projects, Programmes & Supervised Structures"
                : "Faits de la période — Projets, Programmes & Structures sous-tutelle"}
            </h1>
            <p
              style={{
                fontSize: 14,
                color: "var(--cam-text-muted)",
                lineHeight: 1.5,
                margin: 0,
                maxWidth: 720,
              }}
            >
              {isEn
                ? "Before completing the statistical tables in Sections 3 and 4, please indicate the outcomes achieved and personnel movements for your structure since January 1st. Your answers will automatically prepare the required tables."
                : "Avant de remplir les tableaux statistiques des sections 3 et 4, précisez les réalisations et mouvements de personnel de votre structure depuis le 1er janvier. Vos réponses configureront automatiquement les tableaux à renseigner."}
            </p>
          </div>

          {establishmentName && (
            <div
              style={{
                background: "var(--cam-surface-subtle)",
                border: "1px solid var(--cam-border)",
                borderRadius: "var(--cam-radius-control, 6px)",
                padding: "8px 14px",
                fontSize: 12,
                color: "var(--cam-text-muted)",
              }}
            >
              <div style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.03em" }}>
                {isEn ? "Structure" : "Structure"}
              </div>
              <div style={{ fontWeight: 700, color: "var(--cam-text)", marginTop: 2 }}>
                {establishmentName}
              </div>
            </div>
          )}
        </div>

        {s1PermanentCount !== null && (
          <div
            style={{
              marginTop: 16,
              padding: "10px 14px",
              borderRadius: "var(--cam-radius-sm, 6px)",
              background: "rgba(30, 107, 58, 0.08)",
              border: "1px solid rgba(30, 107, 58, 0.25)",
              fontSize: 13,
              color: "var(--cam-green-dark)",
              display: "flex",
              alignItems: "center",
              gap: 8,
            }}
          >
            <span>ℹ️</span>
            <span>
              {isEn
                ? `Permanent staff declared in Section 1 (S1Q15): ${s1PermanentCount} employee(s).`
                : `Effectif permanent déclaré en Section 1 (S1Q15) : ${s1PermanentCount} employé(s).`}
            </span>
          </div>
        )}
      </div>

      {/* Part 1: Outcomes & Achievements (Section 3) */}
      <section
        aria-labelledby="quiz-part1-title"
        style={{
          background: "var(--cam-surface)",
          border: "1px solid var(--cam-border)",
          borderRadius: "var(--cam-radius-md, 8px)",
          padding: "clamp(20px, 3vw, 26px)",
          marginBottom: 20,
          boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
          <span
            style={{
              width: 28,
              height: 28,
              borderRadius: "var(--cam-radius-full, 9999px)",
              background: isPart1Complete ? "var(--cam-green)" : "rgba(11, 31, 20, 0.12)",
              color: isPart1Complete ? "#ffffff" : "var(--cam-text)",
              display: "grid",
              placeItems: "center",
              fontSize: 13,
              fontWeight: 800,
            }}
          >
            {isPart1Complete ? "✓" : "1"}
          </span>
          <h2
            id="quiz-part1-title"
            style={{
              fontSize: 17,
              fontWeight: 800,
              color: "var(--cam-text)",
              margin: 0,
            }}
          >
            {isEn
              ? "Part 1: Placement & Training Outcomes (Section 3)"
              : "Partie 1 : Résultats et réalisations d'insertion / formation (Section 3)"}
          </h2>
        </div>
        <p
          style={{
            fontSize: 13.5,
            color: "var(--cam-text-muted)",
            lineHeight: 1.5,
            margin: "0 0 16px 38px",
          }}
        >
          {isEn
            ? "During the period, did your project or programme record results in any of the following categories? (Unchecked categories will be set to zero)."
            : "Au cours de la période, votre structure ou projet a-t-il enregistré des résultats parmi les catégories suivantes ? (Les catégories non cochées seront enregistrées à zéro)."}
        </p>

        <div style={{ display: "grid", gap: 10, marginLeft: 38 }}>
          {OUTCOME_OPTIONS.map((opt) => {
            const isChecked = outcomes.includes(opt.id);
            return (
              <label
                key={opt.id}
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: 12,
                  padding: "12px 14px",
                  borderRadius: "var(--cam-radius-control, 6px)",
                  border: isChecked
                    ? "2px solid var(--cam-green)"
                    : "1px solid var(--cam-border)",
                  background: isChecked ? "rgba(30, 107, 58, 0.05)" : "var(--cam-surface)",
                  cursor: "pointer",
                  transition: "all 0.15s ease",
                }}
              >
                <input
                  type="checkbox"
                  checked={isChecked}
                  onChange={() => toggleOutcome(opt.id)}
                  style={{
                    marginTop: 3,
                    width: 18,
                    height: 18,
                    accentColor: "var(--cam-green)",
                    cursor: "pointer",
                  }}
                />
                <div>
                  <div style={{ fontSize: "var(--cam-answer-size)", fontWeight: 700, color: "var(--cam-text)" }}>
                    {isEn ? opt.titleEn : opt.titleFr}
                  </div>
                  <div style={{ fontSize: "var(--cam-microcopy-size)", color: "var(--cam-text-muted)", marginTop: 2 }}>
                    {isEn ? opt.descEn : opt.descFr}
                  </div>
                </div>
              </label>
            );
          })}

          {/* Exclusive "None" option */}
          <label
            style={{
              display: "flex",
              alignItems: "flex-start",
              gap: 12,
              padding: "12px 14px",
              borderRadius: "var(--cam-radius-control, 6px)",
              border: noOutcomes
                ? "2px solid var(--cam-green)"
                : "1px dashed var(--cam-border-strong)",
              background: noOutcomes ? "rgba(30, 107, 58, 0.05)" : "var(--cam-surface-subtle)",
              cursor: "pointer",
              transition: "all 0.15s ease",
            }}
          >
            <input
              type="checkbox"
              checked={noOutcomes}
              onChange={handleSelectNoOutcomes}
              style={{
                marginTop: 3,
                width: 18,
                height: 18,
                accentColor: "var(--cam-green)",
                cursor: "pointer",
              }}
            />
            <div>
              <div style={{ fontSize: "var(--cam-answer-size)", fontWeight: 700, color: "var(--cam-text)" }}>
                {isEn
                  ? "No beneficiaries placed or trained during this period"
                  : "Aucun bénéficiaire inséré ou formé au cours de la période"}
              </div>
              <div style={{ fontSize: "var(--cam-microcopy-size)", color: "var(--cam-text-muted)", marginTop: 2 }}>
                {isEn
                  ? "Select this option if no outcome has been recorded yet. Realizations will be initialized to 0."
                  : "Sélectionnez cette option si aucun résultat n'a été enregistré. Les réalisations de la période seront initialisées à 0."}
              </div>
            </div>
          </label>
        </div>
      </section>

      {/* Part 2: Current Staff Headcount (Section 4.1 & 4.2) */}
      <section
        aria-labelledby="quiz-part2-title"
        style={{
          background: "var(--cam-surface)",
          border: "1px solid var(--cam-border)",
          borderRadius: "var(--cam-radius-md, 8px)",
          padding: "clamp(20px, 3vw, 26px)",
          marginBottom: 20,
          boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
          <span
            style={{
              width: 28,
              height: 28,
              borderRadius: "var(--cam-radius-full, 9999px)",
              background: isPart2Complete ? "var(--cam-green)" : "rgba(11, 31, 20, 0.12)",
              color: isPart2Complete ? "#ffffff" : "var(--cam-text)",
              display: "grid",
              placeItems: "center",
              fontSize: 13,
              fontWeight: 800,
            }}
          >
            {isPart2Complete ? "✓" : "2"}
          </span>
          <h2
            id="quiz-part2-title"
            style={{
              fontSize: 17,
              fontWeight: 800,
              color: "var(--cam-text)",
              margin: 0,
            }}
          >
            {isEn
              ? "Part 2: Structure Staff Headcount (Census — Section 4.1 & 4.2)"
              : "Partie 2 : Effectifs en poste dans la structure / le projet (Section 4.1 & 4.2)"}
          </h2>
        </div>
        <p
          style={{
            fontSize: 13.5,
            color: "var(--cam-text-muted)",
            lineHeight: 1.5,
            margin: "0 0 18px 38px",
          }}
        >
          {isEn
            ? "Specify if your structure or project team currently employs staff under the following categories:"
            : "Précisez si votre structure ou équipe de projet emploie actuellement du personnel selon les statuts suivants :"}
        </p>

        <div style={{ display: "grid", gap: 16, marginLeft: 38 }}>
          {/* Question 2.1: Permanent staff */}
          <div
            style={{
              padding: "16px",
              borderRadius: "var(--cam-radius-control, 6px)",
              border: "1px solid var(--cam-border)",
              background: "var(--cam-surface-subtle)",
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, flexWrap: "wrap" }}>
              <div style={{ flex: "1 1 300px" }}>
                <div style={{ fontSize: "var(--cam-question-size)", fontWeight: "var(--cam-question-weight)", lineHeight: "var(--cam-question-line-height)", color: "var(--cam-text)" }}>
                  {isEn
                    ? "2.1 Permanent staff (open-ended contract or civil servant) — Table 4.1"
                    : "2.1 Personnel permanent (CDI ou statutaire) — Tableau 4.1"}
                </div>
                <div style={{ fontSize: "var(--cam-microcopy-size)", color: "var(--cam-text-muted)", marginTop: 2 }}>
                  {isEn
                    ? "Personnel holding open-ended employment contracts or permanent statutory appointment."
                    : "Personnel titulaire d'un contrat à durée indéterminée ou d'un statut permanent dans la structure."}
                </div>
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                <button
                  type="button"
                  onClick={() => setHasPermanentStaff(true)}
                  style={{
                    padding: "8px 18px",
                    borderRadius: "var(--cam-radius-sm, 6px)",
                    border: hasPermanentStaff === true
                      ? "2px solid var(--cam-green)"
                      : "1px solid var(--cam-border)",
                    background: hasPermanentStaff === true ? "var(--cam-green)" : "#ffffff",
                    color: hasPermanentStaff === true ? "#ffffff" : "var(--cam-text)",
                    fontSize: "var(--cam-answer-size)",
                    fontWeight: 700,
                    cursor: "pointer",
                    transition: "all 0.15s ease",
                  }}
                >
                  {isEn ? "Yes" : "Oui"}
                </button>
                <button
                  type="button"
                  onClick={() => setHasPermanentStaff(false)}
                  style={{
                    padding: "8px 18px",
                    borderRadius: "var(--cam-radius-sm, 6px)",
                    border: hasPermanentStaff === false
                      ? "2px solid var(--cam-green)"
                      : "1px solid var(--cam-border)",
                    background: hasPermanentStaff === false ? "var(--cam-green)" : "#ffffff",
                    color: hasPermanentStaff === false ? "#ffffff" : "var(--cam-text)",
                    fontSize: "var(--cam-answer-size)",
                    fontWeight: 700,
                    cursor: "pointer",
                    transition: "all 0.15s ease",
                  }}
                >
                  {isEn ? "No" : "Non"}
                </button>
              </div>
            </div>
            {hasPermanentStaff === true && (
              <div style={{ marginTop: 10, fontSize: 12, color: "var(--cam-green)", fontWeight: 600 }}>
                {isEn
                  ? "✓ Table 4.1 will be open for breakdown by CSP, sex, and age."
                  : "✓ Le tableau 4.1 sera ouvert pour ventiler les effectifs par CSP, sexe et âge."}
              </div>
            )}
            {hasPermanentStaff === false && (
              <div style={{ marginTop: 10, fontSize: 12, color: "var(--cam-text-muted)" }}>
                {isEn
                  ? "Table 4.1 will be recorded as None (cells initialized to zero)."
                  : "Le tableau 4.1 sera enregistré à Néant (cellules initialisées à zéro)."}
              </div>
            )}
          </div>

          {/* Question 2.2: Temporary staff */}
          <div
            style={{
              padding: "16px",
              borderRadius: "var(--cam-radius-control, 6px)",
              border: "1px solid var(--cam-border)",
              background: "var(--cam-surface-subtle)",
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, flexWrap: "wrap" }}>
              <div style={{ flex: "1 1 300px" }}>
                <div style={{ fontSize: "var(--cam-question-size)", fontWeight: "var(--cam-question-weight)", lineHeight: "var(--cam-question-line-height)", color: "var(--cam-text)" }}>
                  {isEn
                    ? "2.2 Temporary staff (fixed-term, seasonal, consultant) — Table 4.2"
                    : "2.2 Personnel temporaire (CDD, vacataires, consultants) — Tableau 4.2"}
                </div>
                <div style={{ fontSize: "var(--cam-microcopy-size)", color: "var(--cam-text-muted)", marginTop: 2 }}>
                  {isEn
                    ? "Personnel holding fixed-term contracts, service providers, or casual staff."
                    : "Personnel sous contrat à durée déterminée, vacataires, consultants ou saisonniers."}
                </div>
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                <button
                  type="button"
                  onClick={() => setHasTemporaryStaff(true)}
                  style={{
                    padding: "8px 18px",
                    borderRadius: "var(--cam-radius-sm, 6px)",
                    border: hasTemporaryStaff === true
                      ? "2px solid var(--cam-green)"
                      : "1px solid var(--cam-border)",
                    background: hasTemporaryStaff === true ? "var(--cam-green)" : "#ffffff",
                    color: hasTemporaryStaff === true ? "#ffffff" : "var(--cam-text)",
                    fontSize: "var(--cam-answer-size)",
                    fontWeight: 700,
                    cursor: "pointer",
                    transition: "all 0.15s ease",
                  }}
                >
                  {isEn ? "Yes" : "Oui"}
                </button>
                <button
                  type="button"
                  onClick={() => setHasTemporaryStaff(false)}
                  style={{
                    padding: "8px 18px",
                    borderRadius: "var(--cam-radius-sm, 6px)",
                    border: hasTemporaryStaff === false
                      ? "2px solid var(--cam-green)"
                      : "1px solid var(--cam-border)",
                    background: hasTemporaryStaff === false ? "var(--cam-green)" : "#ffffff",
                    color: hasTemporaryStaff === false ? "#ffffff" : "var(--cam-text)",
                    fontSize: "var(--cam-answer-size)",
                    fontWeight: 700,
                    cursor: "pointer",
                    transition: "all 0.15s ease",
                  }}
                >
                  {isEn ? "No" : "Non"}
                </button>
              </div>
            </div>
            {hasTemporaryStaff === true && (
              <div style={{ marginTop: 10, fontSize: 12, color: "var(--cam-green)", fontWeight: 600 }}>
                {isEn
                  ? "✓ Table 4.2 will be open for breakdown by CSP, sex, and age."
                  : "✓ Le tableau 4.2 sera ouvert pour ventiler les effectifs par CSP, sexe et âge."}
              </div>
            )}
            {hasTemporaryStaff === false && (
              <div style={{ marginTop: 10, fontSize: 12, color: "var(--cam-text-muted)" }}>
                {isEn
                  ? "Table 4.2 will be recorded as None (cells initialized to zero)."
                  : "Le tableau 4.2 sera enregistré à Néant (cellules initialisées à zéro)."}
              </div>
            )}
          </div>
        </div>
      </section>

      {/* Part 3: Period Recruitments (Section 4.3 to 4.6) */}
      <section
        aria-labelledby="quiz-part3-title"
        style={{
          background: "var(--cam-surface)",
          border: "1px solid var(--cam-border)",
          borderRadius: "var(--cam-radius-md, 8px)",
          padding: "clamp(20px, 3vw, 26px)",
          marginBottom: 24,
          boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
          <span
            style={{
              width: 28,
              height: 28,
              borderRadius: "var(--cam-radius-full, 9999px)",
              background: isPart3Complete ? "var(--cam-green)" : "rgba(11, 31, 20, 0.12)",
              color: isPart3Complete ? "#ffffff" : "var(--cam-text)",
              display: "grid",
              placeItems: "center",
              fontSize: 13,
              fontWeight: 800,
            }}
          >
            {isPart3Complete ? "✓" : "3"}
          </span>
          <h2
            id="quiz-part3-title"
            style={{
              fontSize: 17,
              fontWeight: 800,
              color: "var(--cam-text)",
              margin: 0,
            }}
          >
            {isEn
              ? "Part 3: Period Recruitments (Section 4.3 to 4.6)"
              : "Partie 3 : Recrutements de la période (Section 4.3 à 4.6)"}
          </h2>
        </div>

        {/* Master Gate */}
        <div style={{ marginLeft: 38 }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "flex-start",
              gap: 16,
              padding: "16px",
              borderRadius: "var(--cam-radius-control, 6px)",
              border: "1px solid var(--cam-border)",
              background: "var(--cam-surface-subtle)",
              marginBottom: 16,
              flexWrap: "wrap",
            }}
          >
            <div style={{ flex: "1 1 300px" }}>
              <div style={{ fontSize: "var(--cam-question-size)", fontWeight: "var(--cam-question-weight)", lineHeight: "var(--cam-question-line-height)", color: "var(--cam-text)" }}>
                {isEn
                  ? "Did your structure or project carry out recruitments during the period (since January 1st)?"
                  : "Votre structure ou projet a-t-il effectué des recrutements durant la période (depuis le 1er janvier) ?"}
              </div>
              <div style={{ fontSize: "var(--cam-microcopy-size)", color: "var(--cam-text-muted)", marginTop: 2 }}>
                {isEn
                  ? "Recruitments of permanent, temporary, disabled, or vulnerable workers."
                  : "Recrutements de nouveaux collaborateurs (permanents, temporaires, handicapés, vulnérables)."}
              </div>
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              <button
                type="button"
                onClick={() => setHasRecruitment(true)}
                style={{
                  padding: "8px 18px",
                  borderRadius: "var(--cam-radius-sm, 6px)",
                  border: hasRecruitment === true
                    ? "2px solid var(--cam-green)"
                    : "1px solid var(--cam-border)",
                  background: hasRecruitment === true ? "var(--cam-green)" : "#ffffff",
                  color: hasRecruitment === true ? "#ffffff" : "var(--cam-text)",
                  fontSize: "var(--cam-answer-size)",
                  fontWeight: 700,
                  cursor: "pointer",
                  transition: "all 0.15s ease",
                }}
              >
                {isEn ? "Yes" : "Oui"}
              </button>
              <button
                type="button"
                onClick={() => {
                  setHasRecruitment(false);
                  setRecruitmentTypes([]);
                }}
                style={{
                  padding: "8px 18px",
                  borderRadius: "var(--cam-radius-sm, 6px)",
                  border: hasRecruitment === false
                    ? "2px solid var(--cam-green)"
                    : "1px solid var(--cam-border)",
                  background: hasRecruitment === false ? "var(--cam-green)" : "#ffffff",
                  color: hasRecruitment === false ? "#ffffff" : "var(--cam-text)",
                  fontSize: "var(--cam-answer-size)",
                  fontWeight: 700,
                  cursor: "pointer",
                  transition: "all 0.15s ease",
                }}
              >
                {isEn ? "No" : "Non"}
              </button>
            </div>
          </div>

          {hasRecruitment === false && (
            <div
              style={{
                padding: "12px 14px",
                borderRadius: "var(--cam-radius-sm, 6px)",
                background: "rgba(30, 107, 58, 0.08)",
                border: "1px solid rgba(30, 107, 58, 0.2)",
                fontSize: 13,
                color: "var(--cam-green-dark)",
                display: "flex",
                alignItems: "center",
                gap: 8,
              }}
            >
              <span>✓</span>
              <span>
                {isEn
                  ? "No recruitments to report. All recruitment tables (4.3 to 4.6) will be automatically set to None."
                  : "Aucun recrutement à déclarer pour la période. Les 4 tableaux de recrutement (4.3 à 4.6) seront automatiquement enregistrés à néant."}
              </span>
            </div>
          )}

          {hasRecruitment === true && (
            <div>
              <p
                style={{
                  fontSize: 13.5,
                  fontWeight: 600,
                  color: "var(--cam-text)",
                  margin: "0 0 12px",
                }}
              >
                {isEn
                  ? "Select the recruitment categories carried out:"
                  : "Sélectionnez les catégories de recrutement effectuées :"}
              </p>
              <div style={{ display: "grid", gap: 10 }}>
                {RECRUITMENT_OPTIONS.map((opt) => {
                  const isChecked = recruitmentTypes.includes(opt.id);
                  return (
                    <label
                      key={opt.id}
                      style={{
                        display: "flex",
                        alignItems: "flex-start",
                        gap: 12,
                        padding: "12px 14px",
                        borderRadius: "var(--cam-radius-control, 6px)",
                        border: isChecked
                          ? "2px solid var(--cam-green)"
                          : "1px solid var(--cam-border)",
                        background: isChecked ? "rgba(30, 107, 58, 0.05)" : "var(--cam-surface)",
                        cursor: "pointer",
                        transition: "all 0.15s ease",
                      }}
                    >
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={() => toggleRecruitmentType(opt.id)}
                        style={{
                          marginTop: 3,
                          width: 18,
                          height: 18,
                          accentColor: "var(--cam-green)",
                          cursor: "pointer",
                        }}
                      />
                      <div>
                        <div style={{ fontSize: "var(--cam-answer-size)", fontWeight: 700, color: "var(--cam-text)" }}>
                          {isEn ? opt.titleEn : opt.titleFr}
                        </div>
                        <div style={{ fontSize: "var(--cam-microcopy-size)", color: "var(--cam-text-muted)", marginTop: 2 }}>
                          {isEn ? opt.descEn : opt.descFr}
                        </div>
                      </div>
                    </label>
                  );
                })}
              </div>
              {hasRecruitment && recruitmentTypes.length === 0 && (
                <div
                  style={{
                    marginTop: 10,
                    padding: "8px 12px",
                    borderRadius: "var(--cam-radius-sm, 4px)",
                    background: "rgba(179, 38, 30, 0.08)",
                    border: "1px solid rgba(179, 38, 30, 0.3)",
                    color: "var(--cam-error)",
                    fontSize: 12.5,
                    fontWeight: 600,
                  }}
                >
                  {isEn
                    ? "Please select at least one recruitment category carried out."
                    : "Veuillez cocher au moins une catégorie de recrutement effectuée."}
                </div>
              )}
            </div>
          )}
        </div>
      </section>

      {/* Scope Summary Preview Box */}
      <div
        style={{
          background: "var(--cam-surface-subtle)",
          border: "1px solid var(--cam-border)",
          borderRadius: "var(--cam-radius-md, 8px)",
          padding: "16px 20px",
          marginBottom: 24,
        }}
      >
        <div style={{ fontSize: 13, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.03em", color: "var(--cam-text-muted)", marginBottom: 8 }}>
          {isEn ? "Statistical tables configuration" : "Configuration des tableaux statistiques"}
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 10, fontSize: 12.5 }}>
          <div>
            <strong>{isEn ? "Section 3:" : "Section 3 :"}</strong>{" "}
            {noOutcomes
              ? <span style={{ color: "var(--cam-text-muted)" }}>{isEn ? "None (0)" : "Néant (0)"}</span>
              : <span style={{ color: "var(--cam-green)", fontWeight: 700 }}>{outcomes.length} {isEn ? "outcome(s) active" : "objectif(s) actif(s)"}</span>}
          </div>
          <div>
            <strong>{isEn ? "4.1 Permanent workers:" : "4.1 Permanents :"}</strong>{" "}
            {hasPermanentStaff === true
              ? <span style={{ color: "var(--cam-green)", fontWeight: 700 }}>{isEn ? "To fill" : "À renseigner"}</span>
              : <span style={{ color: "var(--cam-text-muted)" }}>{isEn ? "None" : "Néant"}</span>}
          </div>
          <div>
            <strong>{isEn ? "4.2 Temporary workers:" : "4.2 Temporaires :"}</strong>{" "}
            {hasTemporaryStaff === true
              ? <span style={{ color: "var(--cam-green)", fontWeight: 700 }}>{isEn ? "To fill" : "À renseigner"}</span>
              : <span style={{ color: "var(--cam-text-muted)" }}>{isEn ? "None" : "Néant"}</span>}
          </div>
          <div>
            <strong>{isEn ? "4.3 Permanent recruits:" : "4.3 Recrut. permanents :"}</strong>{" "}
            {hasRecruitment && recruitmentTypes.includes("permanent")
              ? <span style={{ color: "var(--cam-green)", fontWeight: 700 }}>{isEn ? "To fill" : "À renseigner"}</span>
              : <span style={{ color: "var(--cam-text-muted)" }}>{isEn ? "None" : "Néant"}</span>}
          </div>
          <div>
            <strong>{isEn ? "4.4 Temporary recruits:" : "4.4 Recrut. temporaires :"}</strong>{" "}
            {hasRecruitment && recruitmentTypes.includes("temporary")
              ? <span style={{ color: "var(--cam-green)", fontWeight: 700 }}>{isEn ? "To fill" : "À renseigner"}</span>
              : <span style={{ color: "var(--cam-text-muted)" }}>{isEn ? "None" : "Néant"}</span>}
          </div>
          <div>
            <strong>{isEn ? "4.5 Recruits with a disability:" : "4.5 Recrut. handicapés :"}</strong>{" "}
            {hasRecruitment && recruitmentTypes.includes("disability")
              ? <span style={{ color: "var(--cam-green)", fontWeight: 700 }}>{isEn ? "To fill" : "À renseigner"}</span>
              : <span style={{ color: "var(--cam-text-muted)" }}>{isEn ? "None" : "Néant"}</span>}
          </div>
          <div>
            <strong>{isEn ? "4.6 Vulnerable recruits:" : "4.6 Recrut. vulnérables :"}</strong>{" "}
            {hasRecruitment && recruitmentTypes.includes("vulnerable")
              ? <span style={{ color: "var(--cam-green)", fontWeight: 700 }}>{isEn ? "To fill" : "À renseigner"}</span>
              : <span style={{ color: "var(--cam-text-muted)" }}>{isEn ? "None" : "Néant"}</span>}
          </div>
        </div>
      </div>

      {/* Bottom Actions */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
        <button
          type="button"
          onClick={onBack}
          style={{
            background: "transparent",
            border: "1px solid var(--cam-border)",
            borderRadius: "var(--cam-radius-sm, 6px)",
            padding: "10px 20px",
            fontSize: 14,
            fontWeight: 600,
            color: "var(--cam-text)",
            cursor: "pointer",
          }}
        >
          {isEn ? "← Back to Section 1" : "← Retour à la Section 1"}
        </button>

        <button
          type="button"
          onClick={handleProceed}
          disabled={!isFormComplete}
          style={{
            background: isFormComplete ? "var(--cam-green)" : "var(--cam-border-strong)",
            border: "none",
            borderRadius: "var(--cam-radius-sm, 6px)",
            padding: "11px 26px",
            fontSize: 14,
            fontWeight: 700,
            color: "#ffffff",
            cursor: isFormComplete ? "pointer" : "not-allowed",
            boxShadow: isFormComplete ? "0 2px 4px rgba(30, 107, 58, 0.25)" : "none",
            transition: "all 0.15s ease",
          }}
        >
          {isEn ? "Validate & Continue to Tables →" : "Valider et passer aux tableaux →"}
        </button>
      </div>

      {/* Modal: Plausibility Confirmation for Global None */}
      {showPlausibilityModal && (
        <div
          role="dialog"
          aria-modal="true"
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 9999,
            background: "rgba(0, 0, 0, 0.55)",
            backdropFilter: "blur(3px)",
            display: "grid",
            placeItems: "center",
            padding: 16,
          }}
        >
          <div
            style={{
              background: "var(--cam-surface)",
              border: "1px solid var(--cam-border)",
              borderRadius: "var(--cam-radius-md, 8px)",
              padding: "clamp(20px, 4vw, 28px)",
              maxWidth: 520,
              width: "100%",
              boxShadow: "0 8px 24px rgba(0,0,0,0.18)",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
              <span style={{ fontSize: 24 }} aria-hidden="true">
                ⚠️
              </span>
              <h3 style={{ margin: 0, fontSize: 17, fontWeight: 700, color: "var(--cam-text)" }}>
                {isEn ? "Confirm Nil Declaration" : "Confirmation d'une déclaration à néant"}
              </h3>
            </div>
            <p style={{ fontSize: 13.5, color: "var(--cam-text-muted)", lineHeight: 1.5, margin: "0 0 20px" }}>
              {isEn
                ? "You have indicated no beneficiaries placed or trained, no permanent or temporary staff, and no recruitments during this period. All official statistical tables in Sections 3 and 4 will be recorded as None. Do you confirm this situation?"
                : "Vous avez indiqué aucun bénéficiaire inséré ou formé, aucun personnel permanent ou temporaire, et aucun recrutement au cours de cette période. Tous les tableaux statistiques officiels des sections 3 et 4 seront enregistrés à néant. Confirmez-vous cette situation ?"}
            </p>
            <div style={{ display: "flex", justifyContent: "flex-end", gap: 12 }}>
              <button
                type="button"
                onClick={() => setShowPlausibilityModal(false)}
                style={{
                  background: "transparent",
                  border: "1px solid var(--cam-border)",
                  borderRadius: "var(--cam-radius-sm, 6px)",
                  padding: "9px 18px",
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: "pointer",
                }}
              >
                {isEn ? "Modify Answers" : "Modifier mes réponses"}
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowPlausibilityModal(false);
                  commitScopeData();
                  onComplete();
                }}
                style={{
                  background: "var(--cam-green)",
                  border: "none",
                  borderRadius: "var(--cam-radius-sm, 6px)",
                  padding: "9px 18px",
                  fontSize: 13,
                  fontWeight: 700,
                  color: "#ffffff",
                  cursor: "pointer",
                }}
              >
                {isEn ? "Confirm & Open Tables" : "Confirmer la déclaration à néant"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal: Dropped Data Warning */}
      {showDroppedDataModal && (
        <div
          role="dialog"
          aria-modal="true"
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 9999,
            background: "rgba(0, 0, 0, 0.55)",
            backdropFilter: "blur(3px)",
            display: "grid",
            placeItems: "center",
            padding: 16,
          }}
        >
          <div
            style={{
              background: "var(--cam-surface)",
              border: "1px solid var(--cam-border)",
              borderRadius: "var(--cam-radius-md, 8px)",
              padding: "clamp(20px, 4vw, 28px)",
              maxWidth: 520,
              width: "100%",
              boxShadow: "0 8px 24px rgba(0,0,0,0.18)",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
              <span style={{ fontSize: 24 }} aria-hidden="true">
                ⚠️
              </span>
              <h3 style={{ margin: 0, fontSize: 17, fontWeight: 700, color: "var(--cam-text)" }}>
                {isEn ? "Previously Entered Figures Will Be Cleared" : "Données déjà saisies non retenues"}
              </h3>
            </div>
            <p style={{ fontSize: 13.5, color: "var(--cam-text-muted)", lineHeight: 1.5, margin: "0 0 20px" }}>
              {isEn
                ? "Certain tables or outcome categories for which numbers were previously entered are now deselected according to your quiz choices. These numbers will be cleared to zero. Do you wish to proceed?"
                : "Certaines rubriques pour lesquelles des chiffres ont été saisis précédemment ne seront plus déposées conformément à vos choix dans le quiz. Ces chiffres seront réinitialisés à zéro. Souhaitez-vous continuer ?"}
            </p>
            <div style={{ display: "flex", justifyContent: "flex-end", gap: 12 }}>
              <button
                type="button"
                onClick={() => setShowDroppedDataModal(false)}
                style={{
                  background: "transparent",
                  border: "1px solid var(--cam-border)",
                  borderRadius: "var(--cam-radius-sm, 6px)",
                  padding: "9px 18px",
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: "pointer",
                }}
              >
                {isEn ? "Modify Answers" : "Modifier mes choix"}
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowDroppedDataModal(false);
                  commitScopeData();
                  onComplete();
                }}
                style={{
                  background: "var(--cam-green)",
                  border: "none",
                  borderRadius: "var(--cam-radius-sm, 6px)",
                  padding: "9px 18px",
                  fontSize: 13,
                  fontWeight: 700,
                  color: "#ffffff",
                  cursor: "pointer",
                }}
              >
                {isEn ? "Confirm & Clear" : "Confirmer et réinitialiser"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
